name: Scheduled Anime Check

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-anime:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        run: echo "开始执行时间：$(date '+%Y-%m-%d %H:%M:%S')"
        
      - name: Trigger Vercel Function
        id: trigger
        run: |
          echo "调用 Vercel Function..."
          RESPONSE=$(curl -X POST ${{ secrets.VERCEL_FUNCTION_URL }} \
            -H "Content-Type: application/json" \
            -d '{"trigger":"github-action"}' -s)
          echo "API 响应：$RESPONSE"
          
          # 检查响应中是否包含成功信息
          if echo $RESPONSE | grep -q '"success":true'; then
            echo "✅ 检查完成"
          else
            echo "❌ 检查失败"
            exit 1
          fi
